### ISSUE TITLE
Panel: lazy register

### ISSUE THREAD

**Issue by f3l1x** [nettrine/dbal#18]
Don't register DbalPanel in initialize method of container. Move registration to connection factory or sth like that method.

**Comment by mabar** [comment]
I would prefer lazy connection in panel to stay consistent with our other libraries.

**Comment by mabar** [comment]
@f3l1x Looks like implemented https://github.com/nettrine/dbal/commit/c3326ebbbb2d0576af626e8a63addf87a3bbe569#diff-d9e2d714845500cc5b927596a5ccc745R125-R149

**Comment by f3l1x** [comment]
Yup.
