### ISSUE TITLE
Idea: Implement auto-reconect

### ISSUE THREAD

**Issue by novjan** [nettrine/dbal#20]
I have some long-running rabbit consumers. Problem is that they after a some time loose connection to mysql (mysql end non-active connection) and it cause exception `MySQL server has gone away`

Here is a example of what I mean with auto-reconect:
https://github.com/facile-it/doctrine-mysql-come-back

As you can see that it is not that simple change as it was for example for Nette database.

Or if you know something much better way, please share it with me.
I know about this:
```
if ($this->entityManager->getConnection()->ping() !== TRUE) {
	$this->entityManager->getConnection()->close();
	$this->entityManager->getConnection()->connect();
}
```
but I think that something more systematic than copy+past this code in methods/repositories, will be better.

Thank you.

**Comment by f3l1x** [comment]
Hi. I get your point, but I don't know how to resolve it otherwise then https://github.com/facile-it/doctrine-mysql-come-back.

**Comment by f3l1x** [comment]
Closing it now. Feel free to open it and prepare PR. Thanks @novjan
