### ISSUE TITLE
Nette Decorator, Search & DBAL extensions

### ISSUE THREAD

**Issue by solcik** [nettrine/dbal#37]
Nette DI in master register Decorator extension as last, which fixes the problem if somebody register subscribers via Search extension. But new problem occurs, since now Decorator beforeCompile is run after DBAL's beforeCompile, therefore Subscribers do not have tag yet.

https://github.com/nette/di/issues/215#issuecomment-518711237

**Comment by mabar** [comment]
Can you add SearchExtension to the first extensions? I guess it's the most reliable solution and we cannot solve it in nettrine/dbal https://github.com/nette/di/blob/master/src/DI/Compiler.php#L215

**Comment by solcik** [comment]
I am not sure, what that is going to solve?

The problem is that in nette/di@master decorator extension is processed in the end - after the DBAL's extension. So tags added via decorator are not taken into account in DBAL's extension beforeCompile method, which is registering subscribers to eventManager.

**Comment by mabar** [comment]
Oh, I see.
Subscribers have no interface, so they could not be find through it. Alternative solution may be add listeners through config. We have a helper in contributte/di which helps to load services added through extension config. 

https://github.com/contributte/monolog/blob/master/src/DI/MonologExtension.php#L36-L38
and
https://github.com/contributte/monolog/blob/master/src/DI/MonologExtension.php#L87-L96

**Comment by mabar** [comment]
@f3l1x What do you think?

**Comment by solcik** [comment]
As I describe here: https://github.com/nette/di/issues/215#issue-477420682

I am using it for Subscribers, which have interface

`Doctrine\Common\EventSubscriber`.

Listeners do not have interfaces, but these are registred via annotations

`* @ORM\EntityListeners({"Acme\Subscriber\Doctrine\Listener\Sync"})`

**Comment by mabar** [comment]
Sorry, I just noticed it too. Not sure why we choosed tags before 🤔 
Can you send a PR replacing tags with interface?

**Comment by solcik** [comment]
Solved by https://github.com/nettrine/dbal/pull/38
