### ISSUE TITLE
Problem with Nettrine\ORM\DI\OrmCacheExtension

### ISSUE THREAD

**Issue by cubic** [nettrine/dbal#45]
When I use Nettrine\ORM\DI\OrmCacheExtension and Nettrine\Extensions\DI\DoctrineExtensionsExtension at the same time, I got this exception:

Gedmo\Exception\InvalidMappingException

Tree listener was not found on your entity manager, it must be hooked into the event manager

When using Nettrine\Extensions only, everything works fine.

**Comment by mabar** [comment]
Transfered to dbal, ContainerAwareEventManager::getListeners() should always return object instances, not service names
