### ISSUE TITLE
Missing info about cache in doc

### ISSUE THREAD

**Issue by akadlec** [nettrine/dbal#46]
Upgraded to latest 0.6 and failing. Had to add nettrine/cache ext dependency

```
   Nette\DI\ServiceCreationException: Service 'dbal.configuration' (type of Doctrine\DBAL\Configuration): Service of type 'Doctrine\Common\Cache\Cache' not found.
```

**Comment by akadlec** [comment]
Ok, this first touch was in testcase. But now i tested it on real app and had to import nettrine/cache extension to make it work. If it is required, it should be mentioned in doc

**Comment by mabar** [comment]
Fixed by https://github.com/nettrine/dbal/commit/0545b8b390350d57508a79a71e75d566959b8291

**Comment by akadlec** [comment]
👍
