### ISSUE TITLE
Default driver in connection

### ISSUE THREAD

**Issue by aleswita** [nettrine/dbal#53]
When the driver is not set in connection settings, configuration sets **pdo_sqlite** as default.

https://github.com/nettrine/dbal/blob/master/src/DI/DbalExtension.php#L48

But if you are using the **mysqli**, you got an confused error message "SQLSTATE[HY000]: General error: 1 no such table: table_name".

Some "newbies" can be searching problem in wrong place and lost hours, before find solution.
So I think better is removed default driver value and make driver parameter as required.

**Comment by f3l1x** [comment]
I will change to throw an exception if no driver is provided.
