### ISSUE TITLE
Doctrine DBAL 3.x

### ISSUE THREAD

**Issue by xificurk** [nettrine/dbal#66]
`nettrine/dbal` currently depends on `doctrine/dbal` 2.x, which is being sunsetted: https://www.doctrine-project.org/2022/01/22/sunsetting-dbal-2.html

I would like to propose the following for the next release of nettrine/dbal:
- get rid of all the Doctrine deprecations reported on DBAL 2.13
- bump required version of `doctrine/dbal` to `^2.13 || ^3.2`

Reasoning: Supporting both DBAL 2 and 3 would allow more gradual update (and less risky) update in projects using Nettrine. DBAL 2.13 contains forward compatibility layer for DBAL 3, so all code can be updated before jumping to DBAL 3. All DBAL 3.0.x releases contain security vulnerability and should be skipped, the vulnerability patched in 3.1.4, but since we already have 3.2 and 3.3 branches out, I would skip the 3.1.x completely.

If this seems reasonable, I would like to start working on a patch to provide DBAL 3 support. I guess this PR should be merged before that: https://github.com/nettrine/dbal/pull/64.-

**Comment by f3l1x** [comment]
Agreed. Seems like a good approach.

**Comment by f3l1x** [comment]
If you add more tests during you journey, I would be more than happy. ;-)

**Comment by xificurk** [comment]
Resolved by #68

**Comment by dakur** [comment]
Hi guys, do you have any plan when this upgrade will be tagged? Thank you very much.
